added echo

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -17,14 +17,14 @@ jobs:
         java-version: '21'
         distribution: 'temurin'
 
-    - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
+    #- name: Setup Gradle
+    #  uses: gradle/actions/setup-gradle@v4
 
-    - name: Check path
-      run: ls -latrh
+    - name: Debug Repository Files
+      run: ls -la gradlew gradle/wrapper || echo "Gradle wrapper files are missing!"
 
-    - name: Added executable permissions for gradlew
-      run: chmod +x gradlew
+    - name: Ensure Gradle Wrapper Executable
+      run: chmod +x gradlew || echo "gradlew not found!"
 
     - name: Test with Gradle Wrapper
       run: ./gradlew test
